# Site settings
title: "Photographs That Don't Matter"
email: poulos.taylor.w@gmail.com
description: "improving my eye"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: none
